### ISSUE TITLE
NUKI status not updated 

### ISSUE THREAD

**Issue by chrisboer** [jordenc/io.nuki.smartlock#8]
I think due to the difference in EN and NL , Nuki flow don't give any status on lock changes with Homey language on NL

**Comment by jordenc** [comment]
It has been working for weeks for me. I use the English version but that shouldn't matter.

Perhaps you can show the flows that don't work?

**Comment by chrisboer** [comment]
![afbeelding](https://user-images.githubusercontent.com/23163409/29707556-f51e977a-8985-11e7-9165-ae1bdcc40c3a.png)

**Comment by jordenc** [comment]
Strange. Could it be that the action in the last column is giving problems?

This one works well for me, I notice it daily

![schermafbeelding 2017-08-25 om 11 24 58](https://user-images.githubusercontent.com/17727803/29708234-4eca9826-8988-11e7-83d3-c7cbb3c06044.png)

**Comment by chrisboer** [comment]
Why would the action in the last column be a problem it simply sends a message to my phone.

**Comment by jordenc** [comment]
Just want to rule out that the problem is not in push message function.

**Comment by chrisboer** [comment]
Ok do you want me something to check ? or do, are you still on slack ?

**Comment by jordenc** [comment]
Please try if it works if you let Homey say something, like my example. We can then see if it works or not.

If it doesn't work, please double check that the Nuki has the URL for your Homey set correctly:

In a browser, open:
http://<nuki bridge IP>:8080/callback/list?token=<nuki token>

Please make sure that there is 1 URL linking to the IP of Homey. You can paste the output here, there is not any "sensitive" info in there.

**Comment by chrisboer** [comment]
Does not work 
![afbeelding](https://user-images.githubusercontent.com/23163409/29711476-47942826-8995-11e7-88ce-385a5c774f53.png)

**Comment by chrisboer** [comment]
you mean http://192.168.2.27:8084/callback/list?token=mytoken
it gives

callbacks |  
-- | --
0 |  
id | 0
url | "http://192.168.2.18:80/api/app/io.nuki.smartlock/webhook"
1 |  
id | 1
url | "http://192.168.2.18:80/api/app/io.nuki.smartlock/webhook"
2 |  
id | 2
url | "http://192.168.2.30:80/api/app/io.nuki.smartlock/webhook"

**Comment by jordenc** [comment]
Okay, you are still suffering from an old bug.

You can execute:
http://192.168.2.27:8084/callback/remove?id=2&token=mytoken
http://192.168.2.27:8084/callback/remove?id=1&token=mytoken

and I advise you to:
http://192.168.2.27:8084/callback/remove?id=0&token=mytoken
Then restart the Nuki app on Homey (Via settings, go to the Nuki app and press the restart button) so it will restart.

Big tip from my site: Give Homey a static IP address in your router, because the Nuki app will only report correctly if the Homey IP doesn't change. Sadly, this is the only way that it is possible currently, because if I use the static Homey cloud URL https is required, and the Nuki bridge does not support posting to https.

**Comment by chrisboer** [comment]
Ok homey has a static IP, and I have restarted the Nuki App but now I get 

HTTP 503 Unavailable
nothing... on callback list. 

I will restart nuki bridge and Nuki and homey

**Comment by chrisboer** [comment]
Still no callback IP from Homey

**Comment by jordenc** [comment]
Does http://192.168.2.27:8084/callback/list?token=mytoken show the correct IP? Otherwise your Bridge probably also responded 503 to Homey. Sadly, the bridge is a rubbish piece of hardware that times out a lot.

You can manually do this:
http://192.168.2.27:8084/callback/add?token=mytoken&url=http://192.168.2.30:80/api/app/io.nuki.smartlock/webhook

(make sure 192.168.1.30 is the correct IP)

**Comment by chrisboer** [comment]
Ok 

callbacks |  
-- | --
0 |  
id | 0
url | "http://192.168.2.20:80/api/app/io.nuki.smartlock/webhook"

and status also works perfect now.

Many thanks jorden... ;-)

**Comment by CAvE72** [comment]
I had exactly the same issues as Chris and solved the problem with the instructions above. 
Can you please put the instructions into a FAQ, with more detailed instructions which IP address to use (NUKI bridge or Homey) AND point instruct to give Homey also a fixed IP (next to the NUKI bridge)?

**Comment by jordenc** [comment]
Good point. Will update the README.
